name: monorepo
version: 1.0.0
main: index.js
type: module
author: zackerydev
scripts:
  format: biome format --write .
  check: biome check .
  lint: biome check .
dependencies:
  '@actions/core': ^1.11.1
  '@actions/github': ^6.0.1
  '@octokit/webhooks-types': ^7.6.1
  '@slack/web-api': ^7.9.3
  octokit: ^5.0.3
  yaml: ^2.8.1
devDependencies:
  '@biomejs/biome': 2.1.3
  '@types/node': ^24.2.0
  typescript: ^5.9.2
  vitest: ^3.2.4
