---
name: main / ci
on: [push]
jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ./.github/actions/setup
      # - run: node actions/analysis/index.ts
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: analysis
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # 4.2.1
      - uses: ./.github/actions/setup
      - run: pnpm install
      - run: pnpm run -r typecheck
  lint:
    runs-on: ubuntu-latest
    needs: analysis
    strategy:
      matrix:
        commands:
          - check
          - format
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ./.github/actions/setup
      - run: pnpm install
      - run: pnpm  ${{ matrix.commands }}
  cleanup:
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ./.github/actions/setup
      - run: echo "cleanup"




