---
name: meta / setup
permissions:
  issues: write
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - ".github/labels.yaml"
      - ".github/workflows/setup.yaml"
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ./.github/actions/setup
      - name: create labels
        run: node actions/setup/index.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


